[package]
name = "yamengine"
version = "0.1.0"
authors = ["AllenPocekt <AllenPocketGamer@Gmail.com>"]
edition = "2018"


[dependencies]
winit = "0.*"
num_cpus = "1.*"
legion = "0.*"
legion_codegen = "0.*"
nalgebra = "0.*"
wgpu = "0.*"
futures = "0.*"
bytemuck = { version = "1.4", features = ["derive"] }
# lazy_static = "1.*"

[dev-dependencies]
approx = "0.4"

[build-dependencies]
anyhow = "1.*"
fs_extra = "1.*"
glob = "0.*"
shaderc ="0.*"

[[example]]
name = "legion_system"
path = "examples/legion/legion_system.rs"