[package]
name = "YamEngine"
version = "0.1.0"
authors = ["AllenPocekt <AllenPocketGamer@Gmail.com>"]
edition = "2018"


[dependencies]
legion = "0.*"

[[example]]
name ="app_example01"
path = "examples/app/example01.rs"