[package]
name = "yamengine"
version = "0.1.0"
authors = ["AllenPocekt <AllenPocketGamer@Gmail.com>"]
edition = "2018"


[dependencies]
winit = "0.*"
num_cpus = "1.*"
legion = "0.*"
legion_codegen = "0.*"

[[example]]
name = "legion_system"
path = "examples/legion/legion_system.rs"